#!/usr/bin/env bash

cons +asps/staf
cons +asps/Simulation/agetof
cons +pams/gen
cons +asps/
cons +StDb/
cons +StRoot/StarMagField
cons +pams/ %pams/sim/g2r
cons +StarVMC/Geometry

#cons +OnlTools/
#cons +StarDb/
cons +StarVMC/

cons +StRoot/RTS/
cons +StRoot/StAnalysisMaker/
cons +StRoot/StAnalysisUtilities/
cons +StRoot/StAssociationMaker/
cons +StRoot/StBFChain/
cons +StRoot/StBTofCalibMaker/
cons +StRoot/StBTofHitMaker/
cons +StRoot/StBTofMatchMaker/
cons +StRoot/StBTofMixerMaker/
cons +StRoot/StBTofPool/
cons +StRoot/StBTofSimMaker/
cons +StRoot/StBTofUtil/
cons +StRoot/StBbcSimulationMaker/
cons +StRoot/StBeamBackMaker/
cons +StRoot/StBichsel/
cons +StRoot/StChain/
# StDaqLib must be built before StDAQMaker
cons +StRoot/StDaqLib/
cons +StRoot/StDAQMaker/
cons +StRoot/StDataFilterMaker/
cons +StRoot/StDbBroker/
cons +StRoot/StDbLib/
cons +StRoot/StDbUtilities/
cons +StRoot/StDetectorDbMaker/
cons +StRoot/StEEmcDbMaker/
#cons +StRoot/StEEmcPool/
cons +StRoot/StEEmcSimulatorMaker/
cons +StRoot/StEEmcUtil/
cons +StRoot/StEStructPool/
cons +StRoot/StETofCalibMaker/
cons +StRoot/StETofDigiMaker/
cons +StRoot/StETofHitMaker/
cons +StRoot/StETofMatchMaker/
cons +StRoot/StETofQAMaker/
cons +StRoot/StETofUtil/
cons +StRoot/StEmbeddingUtilities/
cons +StRoot/StEmcADCtoEMaker/
cons +StRoot/StEmcCalibrationMaker/
cons +StRoot/StEmcMixerMaker/
cons +StRoot/StEmcPool/
cons +StRoot/StEmcRawMaker/
cons +StRoot/StEmcSimulatorMaker/
cons +StRoot/StEmcTriggerMaker/
cons +StRoot/StEmcUtil/
cons +StRoot/StEpcMaker/
cons +StRoot/StEpdDbMaker/
cons +StRoot/StEpdHitMaker/
cons +StRoot/StEpdUtil/
cons +StRoot/StEtrFastSimMaker/
cons +StRoot/StEvent/
cons +StRoot/StEventCompendiumMaker/
cons +StRoot/StEventMaker/
cons +StRoot/StEventUtilities/
cons +StRoot/StFcsClusterMaker/
cons +StRoot/StFcsDbMaker/
cons +StRoot/StFcsFastSimulatorMaker/
cons +StRoot/StFcsPointMaker/
cons +StRoot/StFcsRawHitMaker/
cons +StRoot/StFcsWaveformFitMaker/
cons +StRoot/StFgtA2CMaker/
cons +StRoot/StFgtClusterMaker/
cons +StRoot/StFgtDbMaker/
cons +StRoot/StFgtPointMaker/
#cons +StRoot/StFgtPool/
cons +StRoot/StFgtRawMaker/
cons +StRoot/StFgtSimulatorMaker/
cons +StRoot/StFgtUtil/
cons +StRoot/StFilterMaker/
cons +StRoot/StFlowAnalysisMaker/
cons +StRoot/StFlowMaker/
cons +StRoot/StFmsDbMaker/
cons +StRoot/StFmsFastSimulatorMaker/
cons +StRoot/StFmsFpsMaker/
cons +StRoot/StFmsHitMaker/
cons +StRoot/StFmsPointMaker/
cons +StRoot/StFmsUtil/
cons +StRoot/StFpdMaker/
cons +StRoot/StFpsRawHitMaker/
cons +StRoot/StFstSimMaker/
cons +StRoot/StFtpcCalibMaker/
cons +StRoot/StFtpcClusterMaker/
cons +StRoot/StFtpcDriftMapMaker/
cons +StRoot/StFtpcMixerMaker/
cons +StRoot/StFtpcSlowSimMaker/
cons +StRoot/StFtpcTrackMaker/
cons +StRoot/StFttSimMaker/
cons +StRoot/StFwdTrackMaker/
cons +StRoot/StGammaMaker/
cons +StRoot/StGenericVertexMaker/
cons +StRoot/StGridCollector/
cons +StRoot/StHbtMaker/
cons +StRoot/StHeavyTagMaker/
cons +StRoot/StHighPtTagsMaker/
#cons +StRoot/StHighptPool/
cons +StRoot/StHitFilterMaker/
cons +StRoot/StHltMaker/
cons +StRoot/StIOMaker/
cons +StRoot/StIstClusterMaker/
cons +StRoot/StIstDbMaker/
cons +StRoot/StIstHitMaker/
cons +StRoot/StIstRawHitMaker/
cons +StRoot/StIstSimMaker/
cons +StRoot/StIstUtil/
cons +StRoot/StJetFinder/
cons +StRoot/StJetMaker/
cons +StRoot/StLaserAnalysisMaker/
cons +StRoot/StMCFilter/
cons +StRoot/StMagF/
cons +StRoot/StMcAnalysisMaker/
cons +StRoot/StMcEvent/
cons +StRoot/StMcEventMaker/
cons +StRoot/StMcQaMaker/
cons +StRoot/StMiniMcEvent/
cons +StRoot/StMiniMcMaker/
cons +StRoot/StMtdCalibMaker/
cons +StRoot/StMtdEvtFilterMaker/
cons +StRoot/StMtdHitMaker/
cons +StRoot/StMtdMatchMaker/
cons +StRoot/StMtdQAMaker/
cons +StRoot/StMtdSimMaker/
cons +StRoot/StMtdUtil/
cons +StRoot/StMuAnalysisMaker/
cons +StRoot/StMuDSTMaker/
cons +StRoot/StPCollTagMaker/
cons +StRoot/StPass0CalibMaker/
cons +StRoot/StPeCMaker/
cons +StRoot/StPicoDstMaker/
cons +StRoot/StPicoEvent/
cons +StRoot/StPidAmpMaker/
cons +StRoot/StPmdCalibrationMaker/
cons +StRoot/StPmdClusterMaker/
cons +StRoot/StPmdDiscriminatorMaker/
cons +StRoot/StPmdReadMaker/
cons +StRoot/StPmdSimulatorMaker/
cons +StRoot/StPmdUtil/
cons +StRoot/StPreEclMaker/
cons +StRoot/StPxlClusterMaker/
cons +StRoot/StPxlDbMaker/
cons +StRoot/StPxlHitMaker/
cons +StRoot/StPxlRawHitMaker/
cons +StRoot/StPxlSimMaker/
cons +StRoot/StPxlUtil/
cons +StRoot/StRefMultCorr/
cons +StRoot/StRichPool/
cons +StRoot/StRrsMaker/
cons +StRoot/StSecondaryVertexMaker/
#cons +StRoot/StShadowMaker/
cons +StRoot/StSpectraPool/
#cons +StRoot/StSpinMaker/
#cons +StRoot/StSpinPool/
cons +StRoot/StSsdDaqMaker/
cons +StRoot/StSsdDbMaker/
cons +StRoot/StSsdFastSimMaker/
cons +StRoot/StSsdPointMaker/
cons +StRoot/StSsdSimulationMaker/
cons +StRoot/StSsdUtil/
cons +StRoot/StSstDaqMaker/
cons +StRoot/StSstPointMaker/
cons +StRoot/StSstUtil/
cons +StRoot/StStarLogger/
cons +StRoot/StStrangeMuDstMaker/
cons +StRoot/StStrangeTagsMaker/
cons +StRoot/StSvtCalibMaker/
cons +StRoot/StSvtClassLibrary/
cons +StRoot/StSvtClusterMaker/
cons +StRoot/StSvtDaqMaker/
cons +StRoot/StSvtDbMaker/
cons +StRoot/StSvtPool/
cons +StRoot/StSvtSeqAdjMaker/
cons +StRoot/StSvtSimulationMaker/
cons +StRoot/StTableUtilities/
cons +StRoot/StTagsMaker/
cons +StRoot/StTofCalibMaker/
cons +StRoot/StTofHitMaker/
cons +StRoot/StTofMaker/
cons +StRoot/StTofPool/
cons +StRoot/StTofSimMaker/
cons +StRoot/StTofUtil/
cons +StRoot/StTofpMatchMaker/
cons +StRoot/StTofrMatchMaker/
cons +StRoot/StTpcDb/
cons +StRoot/StTpcHitMaker/
cons +StRoot/StTpcHitMoverMaker/
cons +StRoot/StTpcRSMaker/
cons +StRoot/StTreeMaker/
cons +StRoot/StTrgDatFileReader/
cons +StRoot/StTrgMaker/
cons +StRoot/StTriggerDataMaker/
cons +StRoot/StTriggerUtilities/
cons +StRoot/StTrsMaker/
cons +StRoot/StUtilities/
cons +StRoot/StVpdCalibMaker/
cons +StRoot/StVpdSimMaker/
cons +StRoot/StXTrakMaker/
cons +StRoot/StZdcVertexMaker/
cons +StRoot/St_QA_Maker/
cons +StRoot/St_TLA_Maker/
cons +StRoot/St_base/
cons +StRoot/St_baseTest/
cons +StRoot/St_ctf_Maker/
cons +StRoot/St_db_Maker/
cons +StRoot/St_emc_Maker/
cons +StRoot/St_geant_Maker/
cons +StRoot/St_pp2pp_Maker/
cons +StRoot/St_sdm_Maker/
cons +StRoot/St_srs_Maker/
cons +StRoot/St_tcl_Maker/
cons +StRoot/St_trg_Maker/
cons +StRoot/Star2Root/
cons +StRoot/StarClassLibrary/
cons +StRoot/StarGenerator/ %StRoot/StarGenerator/Pythia8_1_62
cons +StRoot/StarMagField/
cons +StRoot/StarRoot/
cons +StRoot/StdEdxY2Maker/
cons +StRoot/Sti/
cons +StRoot/StiCA/
cons +StRoot/StiIst/
cons +StRoot/StiMaker/
cons +StRoot/StiPxl/
cons +StRoot/StiRnD/
cons +StRoot/StiSsd/
cons +StRoot/StiSvt/
cons +StRoot/StiTpc/
cons +StRoot/StiUtilities/
cons +StRoot/Stl3RawReaderMaker/
cons +StRoot/Stl3Util/
#cons +StRoot/Stv/
#cons +StRoot/StvMaker/
#cons +StRoot/StvSeed/
cons +StRoot/StvUtil/
cons +StRoot/TPCCATracker/
